influxdata/influxdb-client-python

CHANGELOG.md
README.rst
influxdb_client/client/write/point.py
influxdb_client/client/write_api.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py

Added possibility to write dictionary-style object 

---

README.rst
influxdb_client/client/write_api.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py

feat: Add support to write by byte array (#26)

---

CHANGELOG.md
influxdb_client/client/flux_table.py
tests/test_FluxObject.py

The `FluxRecord` supports dictionary-style access:
```python
record = FluxRecord()
record["table"] = 0
record["_start"] = _time
record["_stop"] = _time
record["_time"] = _time
record["_value"] = 1.0
record["_field"] = 'water level'
record["_measurement"] = 'h2o'
record["location"] = 'coyote_creek'
print(table.records[0]["_measurement"])
print(table.records[0]["_field"])
print(table.records[0]["_value"])
```

FluxRecord supports dictionary-style access

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApi.py

Closes #46
InfluxDBClient default `org` is used by `WriteAPI`

fix: use default org

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client.py
influxdb_client/client/write_api.py
tests/test_WriteApi.py

Add support for default tags (#50)

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApiBatching.py

Fix default tags for write batching, added new test.

---

CHANGELOG.md
influxdb_client/api_client.py
openapi-generator/src/main/resources/python/api_client.mustache
tests/test_TasksApi.py
tests/test_WriteApiBatching.py

feat: add User-Agent request header

---

README.rst
tests/test_AuthorizationApi.py
tests/test_BucketsApi.py
tests/test_TasksApi.py

Add docs about local testing

---

CHANGELOG.md
influxdb_client/api_client.py
openapi-generator/src/main/resources/python/api_client.mustache

fix: Correctly close connection pool manager at exit

---

.gitignore
CHANGELOG.md
influxdb_client/client/write_api.py
influxdb_client/rest.py
openapi-generator/src/main/resources/python/rest.mustache
tests/test_WriteApiPickle.py

Closes #69
`InfluxDBClient` and `WriteApi` could serialized by [pickle](https://docs.python.org/3/library/pickle.html#object.__getstate__) (python3.7 or higher)

fix: rest_api and write_api is able to be pickled

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py
tests/test_QueryApiDataFrame.py

fix: Optimize serializing data into Pandas DataFrame

---

README.rst

Closes #82
Update Readme to reflect this client library supports 2.0 and 1.8+.

Update readme for InfluxDB 1.8+

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApiBatching.py

Related-to #80
Fixed a possibility to generate empty write batch

fix: avoid to generate an empty write batch

---

CHANGELOG.md
README.rst
influxdb_client/client/write_api.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py

feat: support for writing pandas DataFrame

---

CHANGELOG.md
influxdb_client/client/delete_api.py
tests/test_DeleteApi.py

Closes #86
BREAKING CHANGE: Fixed parameters in delete api - now delete api accepts also bucket name and org name instead of only ids.

fix: Fixed parameters in delete api #86

---

CHANGELOG.md
influxdb_client/client/influxdb_client.py
tests/test_BucketsApi.py
tests/test_InfluxDBClient.py

feat: remove trailing slash from connection URL

---

README.rst

reStructuredText doesn't allow link insertion in bold text block
Edit in README to fix wrong link rendering behavior to in influxdb-python link.

Fixed link formating in README

---

.gitignore
CHANGELOG.md
extra-requirements.txt
influxdb_client/client/write_api.py
influxdb_client/extras.py
tests/test_BucketsApi.py
tests/test_WriteApi.py
tests/test_WriteApiDataFrame.py

feat: DataFrame optimalization

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

fix: mapping dictionary without timestamp and tags into LineProtocol

---

.gitignore
CHANGELOG.md
influxdb_client/client/write/point.py
influxdb_client/client/write_api.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py
tests/test_point.py

fix: writes uses precision from Point instead a default precision

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Closes #112 
Auto-converts timestamp with timezone to UTC.

feat: convert timezone to UTC if tzinfo exists

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApi.py

fix: appending default tags for single Point

---

CHANGELOG.md
influxdb_client/client/query_api.py

Closes #114
Add "query_data_frame_stream" method to reduce RAM usage.

Add query_data_frame_stream method

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Related to https://github.com/influxdata/influxdb-client-java/issues/127
* serialization of `\n`, `\r` and `\t` to Line Protocol
* `=` is valid sign for measurement name

fix: serialization of `\n`, `\r` and `\t` to Line Protocol, `=` is valid sign for measurement name 

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE
.github/semantic.yml

1. Added GitHub template for Bug report
2. Added GitHub template for Feature request
3. Prepared configuration for Semantic Pull Requests

docs: added GitHub template for Bug report, Feature request, added configuration for Semantic Pull Requests

---

README.rst

The url for Line Protocol pointed to the online documentation version 1.6, which prompts users to visit the 1.8 version. This change links straight to the 1.8 version.

docs: update Line Protocol doc url from 1.6 to 1.8

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
influxdb_client/client/write_api.py
tests/test_WriteApiDataFrame.py

fix: fixed serialization of DataFrame with empty (NaN) values, fixed escaping whitespaces, fixed order of tags

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Data points uses `microseconds` from time delta to better precision.
see also https://github.com/influxdata/influxdb-python/pull/811

feat: use microseconds resolutions for data points

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApiBatching.py

fix: use Retry-After header value for Retryable error codes

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client.py
tests/config-disabled-ssl.ini
tests/test_InfluxDBClient.py

Closes #142 
The `verify_ssl` could be configured via config file or environment properties.

feat: skip of verifying SSL certificate could be configured via config file or environment properties

---

.circleci/config.yml
CHANGELOG.md
README.rst
docs/usage.rst
examples/example.py
examples/import_data_set.py
examples/import_data_set_multiprocessing.py
examples/ingest_dataframe_default_tags.py
examples/iot_sensor.py
examples/nanosecond_precision.py
examples/query.py
examples/query_from_file.py
influxdb_client/client/influxdb_client.py
notebooks/realtime-stream.ipynb
notebooks/stock-predictions.ipynb
notebooks/stock_predictions_import_data.py
notebooks/telegraf.conf
scripts/influxdb-onboarding.sh
scripts/influxdb-restart.sh
tests/base_test.py
tests/config-disabled-ssl.ini
tests/config.ini
tests/test_InfluxDBClient.py
tests/test_QueryApiDataFrame.py
tests/test_WriteApi.py
tests/test_WriteApiDataFrame.py
tests/test_WriteApiPickle.py
tests/test_point.py

Closes #149
- default port changed to 8086

chore: default port changed to 8086

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py

Closes #150
- `WriteApi` supports `Iterable` type - Tuple, List, ...

feat: WriteApi supports Iterable type

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
tests/test_WriteApiDataFrame.py

Closes #153 
* string fields are correctly serialized

fix: field string values are correctly escaped in DataFrame serialization

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client.py
tests/config-ssl-ca-cert.ini
tests/test_InfluxDBClient.py

Closes #157
- added possibility to specify certificate file path to verify the peer

feat: added possibility to specify certificate file path to verify the peer

---

CHANGELOG.md
influxdb_client/client/exceptions.py
influxdb_client/client/write/retry.py
tests/test_InfluxDBError.py
tests/test_WritesRetry.py

* message scope is **warning**
* The message looks like:
_The retriable error occurred during request. Reason: 'org 04014de4ed590000 has exceeded limited_write plan limit'. Retry in 63s._

feat: added logging message for retries

---

.circleci/config.yml
CHANGELOG.md
setup.py

chore: added support for Python 3.9

---

CHANGELOG.md
setup.py

Closes #
Installing tests is not generally desirable in the first place, but particularly not in the global top level `tests` package.

Exclude tests from installs

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
tests/test_WriteApiDataFrame.py

Closes #169 
Skip DataFrame rows without data - all fields are nan

fix: skip DataFrame rows without data

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py
tests/test_FluxCSVParser.py

CSV parser is able to parse export from UI

feat: CSV parser is able to parse export from UI

---

.circleci/config.yml
docker/aws_lambda_layer/Dockerfile
docker/aws_lambda_layer/README.md

Closes #106 
Docker image which allows user to create a zip file with all Python dependencies for a custom AWS Lambda function (by default with influxdb-client). This should be within the limit of 10MB per single browser upload (~3,5MB with just the influxdb-client-python library). If the zip archive is uploaded to a custom Lambda Layer then user is able to keep using the Console IDE for editing main Lambda function.

chore: aws lambda layer

---

CHANGELOG.md
influxdb_client/client/influxdb_client.py

Helps with #176 
Allow passing proxy setting as options to the `InfluxDBClient`.
For example:
```
client = InfluxDBClient(url="https://public-url", token=token, org=org, proxy="http://127.0.0.1:3128")
```

feat: Allow providing proxy option to InfluxDBClient

---

docker/aws_lambda_layer/Dockerfile

using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
- [*] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [*] Sign …

chore: use `--no-cache-dir` flag to `pip` in dockerfiles to save space

---

.gitignore
CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
influxdb_client/client/write/point.py
tests/test_WriteApiDataFrame.py

Fix the possibility of data corruption by using a much simpler
regular expression to fix up the results.
Also avoid mutating the DataFrame that's been passed in
by making a shallow copy. This changes semantics
so that if a column mentioned in `PointSettings` exists
in the actual data too, it won't be overridden.
Also change the `test_write_data_frame` test, which is essentially benchmarking
the `data_frame_to_list_of_points` function, so that it just does that
so it can easily be run on a local machine and is independent
of network speed. It runs in about 10s, which is comparable
to the previous performance.
Closes #182

chore: influxdb_client/client/write: fix data_frame_to_list_of_points

---

influxdb_client/client/write/point.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py
tests/test_gzip.py
tests/test_point.py

Floating point whole numbers are encoded with a trailing `.0`
which is unnecessary (integers are encoded with a trailing `i` character),
is different from other line-protocol encoders, and makes encoded
entries longer than necessary, so strip that suffix when it's seen.

chore: influxdb_client/client/write: strip .0 on float values

---

CHANGELOG.md
README.rst
docs/api.rst
docs/conf.py
docs/usage.rst
influxdb_client/__init__.py

Closes #188
Added documentation about `DeleteApi`.

docs: documentation about delete endpoint

---

CHANGELOG.md
influxdb_client/client/tasks_api.py
tests/test_TasksApi.py

Closes #
I was trying to get a single run for a task and was getting the following error:
`Got an unexpected keyword argument 'run_id' to method get_tasks_id_runs`
From what I could tell, the lib was using the wrong function to get a specific run by id.

fix(tasks_api): fixed get_run to use proper function

---

README.rst

Related to https://github.com/influxdata/influxdb-client-python/commit/a1f9826590355e9cd32a198ae164560894c2bd58#r47111313
Fixed an example about how to write Pandas.DataFrame

docs: fix an example about how to write Pandas.DataFrame

---

CHANGELOG.md
README.rst
examples/import_data_set.py
examples/import_data_set_multiprocessing.py
examples/influxdb_18_example.py
examples/ingest_dataframe_default_tags.py
examples/iot_sensor.py
examples/nanosecond_precision.py
examples/query.py
examples/query_from_file.py
examples/rx_playground.py
notebooks/stock_predictions_import_data.py
tests/test_QueryApiDataFrame.py
tests/test_QueryApiStream.py
tests/test_WriteApi.py
tests/test_WriteApiBatching.py
tests/test_WriteApiDataFrame.py
tests/test_WriteApiPickle.py
tests/test_gzip.py
tests/test_health.py

Related to #190.
Use `close` rather than `__del__` in docs, tests and examples.
I could have added a close method to `ApiClient` for consistency but I didn't.
[This SO answer](https://stackoverflow.com/a/1481512/4653485) provides a nice explanation of what `__del__` is and its limitations and why using it is not a great pattern.
At least, I think the content should be in the close method, and the close method should be called in `__del__` rather than the opposite.
Anyway, as said in #190, a context manager would be a nice way of solving the whole thing.
Until then, I figured using `close` in the docs would be better.

docs: replace calls to __del__ with calls to close

---

CHANGELOG.md
README.rst
docs/usage.rst
examples/README.md
examples/import_data_set_sync_batching.py

Closes #198 
- added an example how to use RxPY and sync batching
- added examples/README.md with description for examples
- fixed generating usage doc

docs: added an example how to use RxPY and sync batching

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client.py
tests/config.toml
tests/test_InfluxDBClient.py

Closes #201
Allow configuring client via TOML file - InfluxDB 2 config file.

feat: client could be configured via TOML file

---

CHANGELOG.md
influxdb_client/rest.py

Closes #206
Remove the use of Mozilla's root certificates as default.

Remove the use of Mozilla's root certificates and certifi.where()

---

CHANGELOG.md
influxdb_client/domain/bucket_retention_rules.py
influxdb_client/domain/date_time_literal.py
tests/test_BucketsApi.py

The generated API validate values in domain object.
The https://github.com/influxdata/influxdb/pull/20911 change api:
so our integrations test agains nightly build failing:
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-python/832/workflows/ced8a9ae-fc23-46bf-8ec9-a4daed7dd94c/jobs/2923

feat(swagger): Allow setting shard-group durations for buckets via API

---

CHANGELOG.md
influxdb_client/client/tasks_api.py
tests/test_TasksApi.py

Closes https://github.com/influxdata/influxdb-client-python/issues/216

fix: fixing bugs in clone_task function

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client.py
tests/config.ini
tests/config.toml
tests/test_InfluxDBClient.py

Closes #204
Allow to configure a connection pool maxsize.

feat: allow to configure a connection pool maxsize

---

CHANGELOG.md
README.rst
examples/query.py
influxdb_client/client/query_api.py
influxdb_client/client/util/date_utils.py
influxdb_client/client/write/point.py
tests/test_QueryApi.py

Closes #219 
Example of usage:
```python
p = {"_start": datetime.timedelta(hours=-1),
"_location": "Prague",
"_desc": True,
"_floatParam": 25.1,
"_every": datetime.timedelta(minutes=5)
}
tables = query_api.query('''
from(bucket:"my-bucket") |> range(start: _start)
|> filter(fn: (r) => r["_measurement"] == "my_measurement")
|> filter(fn: (r) => r["_field"] == "temperature")
|> filter(fn: (r) => r["location"] == _location and r["_value"] > _floatParam)
|> aggregateWindow(every: _every, fn: mean, createEmpty: true)        
|> sort(columns: ["_time"], desc: _desc) 
''', params=p)
```

feat:  query bind parameters

---

CHANGELOG.md
influxdb_client/client/influxdb_client.py
influxdb_client/configuration.py
influxdb_client/rest.py
tests/test_InfluxDBClient.py
tests/test_WriteApi.py

Closes #221
Correctly pass configured timeout into `urllib3`.

fix: pass configured timeout to HTTP client

---

README.rst

Closes #226 
Added note that the client is not compatible with old-one.

docs: add note that the client is not compatible with the old-one

---

CHANGELOG.md
influxdb_client/client/write_api.py
tests/test_WriteApi.py

Closes #234 
Added a default empty dict for `tags` in dictionary-style object.

fix: write a dictionary-style object without tags

---

CHANGELOG.md
README.rst
examples/import_data_set_sync_batching.py
influxdb_client/client/write/retry.py
influxdb_client/client/write_api.py
tests/test_WriteApiBatching.py
tests/test_WriteOptions.py
tests/test_WritesRetry.py

This PR changes the default retry strategy to Full Jitter. 
Related discussion is https://github.com/influxdata/influxdb/pull/19722#discussion_r518796754
Original retry formula:
`retry_interval * exponential_base^(attempts-1) + random(jitter_interval)`
Purposed exponential random retry formula:
Retry delay is calculated as random value within the interval  
[`retry_interval * exponential_base^(attempts-1) and
retry_interval * exponential_base^(attempts)`]
Example for ``retry_interval=5_000, exponential_base=2, max_retry_delay=125_000`` 
Retry delays are random distributed values within the ranges of 
``[5_000-10_000, 10_000-20_000, 20_000-40_000, 40_000-80_000, 80_000-125_000]``

feat: implement exponential random retry strategy

---

CHANGELOG.md
examples/buckets_management.py
influxdb_client/client/authorizations_api.py
influxdb_client/client/bucket_api.py
influxdb_client/client/labels_api.py
influxdb_client/client/organizations_api.py
influxdb_client/client/tasks_api.py
tests/test_BucketsApi.py

Closes #
adds the ability to page with the find_buckets function.

feat: add paging to find functions

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Related to #239
Added detail error message for not supported type of `Point.field`

chore: add detail error message for not supported type of `Point.field`

---

CHANGELOG.md
influxdb_client/client/util/date_utils.py
tests/test_DateHelper.py

Closes #73
Added possibility to specify default timezone for `datetime`s without `tzinfo`. 
It is useful for specify system timezone:
```python
from dateutil.tz import tzlocal
from influxdb_client.client.util import date_utils
from influxdb_client.client.util.date_utils import DateHelper
date_utils.date_helper = DateHelper(timezone=tzlocal())
```

feat: add possibility to specify default `timezone` for datetimes without `tzinfo`

---

CHANGELOG.md
README.rst

docs: fix incorrect env var description

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
tests/test_WriteApiDataFrame.py

Closes #252 
Fixed serializing `numpy` float types into Line Protocol.
- https://numpy.org/doc/stable/reference/arrays.scalars.html#floating-point-types

fix: serialize numpy floats

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client.py
influxdb_client/configuration.py
tests/config.ini
tests/config.toml
tests/test_InfluxDBClient.py

feat: add option for basic auth when using influxdb 1.8 compatibility API
Closes #262
Add an additional option ```auth_basic: True|False``` for the InfluxDBClient, which allows to use the client in cases where reverse proxies are being used for authentication instead of InfluxDBs own authentication (applies only for InfluxDB 1.8 forward compatibility API).
Using reverse proxies is quite a common setup, so this makes it easier to integrate in such scenarios.

feat: config option to allow basic auth

---

README.rst
examples/query.py
influxdb_client/client/flux_csv_parser.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/query_api.py
tests/base_test.py
tests/config.ini
tests/config.toml
tests/test_InfluxDBClient.py
tests/test_QueryApi.py

This PR adds support for Flux Query profiler - https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/profiler/

feat: flux query profiler

---

influxdb_client/__init__.py
influxdb_client/api_client.py
influxdb_client/configuration.py
influxdb_client/version.py
setup.py
tests/test_WriteApiBatching.py

The version of client is specified on one place - useful for simple release and update management.

chore: version of client is specified on one place

---

CHANGELOG.md
examples/buckets_management.py
influxdb_client/client/bucket_api.py
influxdb_client/client/query_api.py
influxdb_client/client/util/helpers.py
influxdb_client/client/write_api.py
tests/base_test.py
tests/test_AuthorizationApi.py
tests/test_BucketsApi.py
tests/test_Helpers.py

Closes #240
The org parameter can be specified as `ID`, `Name` or `Organization`. If API requires the ID of Organization then this `id` is leverage via `organization_api`.

feat: Org parameter can be specified as ID, Name or Organization Object

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
influxdb_client/client/write_api.py
tests/test_WriteApiDataFrame.py

Closes #245
The `dataframe_serializer.py` supports `write_precision`.

fix: supports `write_precision` for write Pandas DataFrame

---

CHANGELOG.md
influxdb_client/client/flux_table.py

`__repr__` methods are a convenient feature for exploring objects interactively - i.e. in an interactive shell or a Jupyter notebook. The default representation of an object basically just identifies the type:
```
<influxdb_client.client.flux_table.FluxRecord at 0x7f5720b63460>
```
By defining `__repr__`, objects can display themselves with more useful information:
```
<FluxTable: 11 columns, 360 records>
FluxColumn(7, label='_measurement', data_type='string', group=True, default_value='')
<FluxRecord field=counter value=282.0>
```
There are loose conventions for how reprs are formatted, though I'm not aware of any reference for them. They generally fit on one line, to simplify formatting in containers. If it's practical to fit in all the information to reconstruct the object, the repr …

feat: add __repr__ methods for FluxTable, FluxColumn, FluxRecord

---

CHANGELOG.md
influxdb_client/client/influxdb_client.py
tests/config-enabled-proxy.ini
tests/test_InfluxDBClient.py

The proxy option was not parsed in the config file.
Closes #

fix: set proxy server in config file

---

CHANGELOG.md
examples/README.md
examples/ingest_large_dataframe.py
influxdb_client/client/write/dataframe_serializer.py
influxdb_client/client/write_api.py
tests/test_WriteApiDataFrame.py

Closes #291
1. The `dataframe_serializer` supports batching - serialize DataFrame rows in batches corresponding to `batch_size`.
2. Added an example how to import large DataFrame

feat: `dataframe_serializer` supports batching

---

CHANGELOG.md
README.rst
docs/usage.rst
influxdb_client/client/influxdb_client.py
influxdb_client/configuration.py
influxdb_client/rest.py
tests/test_InfluxDBClient.py
tests/test_WriteApi.py

Closes #300 
Closes #294
1. added `proxy_headers` to configuration options
1. added docs how to configure proxy

feat: add `proxy_headers` to configuration options

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Closes #302
The backslash does not have to be escaped in `Measurement`, `Tag key`, `Tag value` and `Field key`. For more info see:
https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#special-characters

fix: backslash escaping in serialization to Line protocol

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Closes #305
Add supports for serialize `numpy` types.

feat: supports numpy types in serialization to Line protocol

---

CHANGELOG.md
docker/aws_lambda_layer/Dockerfile

i was following the instructions here: https://github.com/influxdata/influxdb-client-python/tree/master/docker/aws_lambda_layer#readme
but noticed that the zip file created contained files that start with the `/python/` prefix. To be compatible with aws lambda, the packages should be in the root.
previous zip structure:
```
(base) ➜  kinesisToInfluxDBCloud unzip -vl python.zip | head
Archive:  python.zip
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
0  Stored        0   0% 08-17-2021 22:25 00000000  python/
0  Stored        0   0% 08-17-2021 22:25 00000000  python/rx/
0  Stored        0   0% 08-17-2021 22:25 00000000  python/rx/py.typed
0  Stored        0   0% 08-17-2021 22:25 00000000  python/rx/core/
9565 …
```

fix: ensuring aws lambda compatible zip

---

CHANGELOG.md
README.rst
conda/meta.yaml

This PR bring support for deploying `influxdb-client-python` to Anaconda.org - https://anaconda.org/influxdata/influxdb_client

chore(release): deploy package to Anaconda.org

---

README.rst
docs/usage.rst

Closes #314
Added link about `Nanosecond precision` to usage page:

docs: add link about `Nanosecond precision` to usage page

---

CHANGELOG.md
influxdb_client/client/query_api.py
tests/test_QueryApi.py

Closes #318
Add supports for array in query parameters. Following queries are now supported:
```python
query_api.query('''
from(bucket: "my-bucket")
|> range(start: -6h, stop: now())
|> filter(fn: (r) => contains(value: r.location, set: bars))
|> last()
''', params={"bars": ["Prague", "Berlin", "Rome"]})
```

feat: add supports for array expressions in query parameters

---

CHANGELOG.md
examples/README.md
examples/query_response_to_json.py
influxdb_client/client/flux_table.py
tests/query_output.json
tests/test_FluxCSVParser.py
tests/test_Thresholds.py

Closes #311 
The result of query could be serialized into JSON by:
```python
import json
from influxdb_client.client.flux_table import FluxStructureEncoder
output = json.dumps(tables, cls=FluxStructureEncoder, indent=2)
print(output)
```

feat: add support for serialization FluxTable into JSON

---

CHANGELOG.md
influxdb_client/client/delete_api.py
tests/test_DeleteApi.py

Closes #313
The use can use `datetime` without timezone as a parameter for `delete_api`.

feat: `delete_api` also accept `datetime` as a value for `start` and `stop`

---

CHANGELOG.md
examples/buckets_management.py
influxdb_client/client/bucket_api.py
influxdb_client/client/organizations_api.py
influxdb_client/client/users_api.py
tests/base_test.py
tests/test_BucketsApi.py
tests/test_OrganizationsApi.py
tests/test_UsersApi.py

Closes #357 
Updated management API:
- `BucketsApi` - add possibility to: `update`
- `OrganizationsApi` - add possibility to: `update`
- `UsersApi` - add possibility to: `update`, `delete`, `find`

feat: update management API - `BucketsApi`, `OrganizationsApi`, `UsersApi`

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
tests/test_WriteApiDataFrame.py

Related to https://community.influxdata.com/t/writing-entries-gives-invalid-field-format-error-but-only-if-2-tags-are-added-together-separately-works-fine/22368
Fixed `regexp` for removing leading comma for NaN values.

fix: correct serialization empty columns into LineProtocol [DataFrame]

---

.gitignore
CHANGELOG.md
docs/api.rst
influxdb_client/client/util/multiprocessing_helper.py
influxdb_client/client/write_api.py
tests/test_MultiprocessingWriter.py

Closes #350
Add helper which help user to write data in separate OS process - it is useful for latency sensitive use-cases.

feat: add MultiprocessingWriter to help user write data in independent OS process

---

CHANGELOG.md
influxdb_client/client/exceptions.py
tests/test_InfluxDBError.py

This fixes an AttributeError while handling another error raised from a failed POST request. In detail, when a POST request fails during the connection establishment there is no http response, so when an InfluxDBError instance is constructed the response field is None . This leads to an AttributeError later when the response.data is accessed. The fix is a trivial None check in the InfluxDBError constructor so that a None response argument properly works.
I was able to reproduce it due to the expired ssl certificate error with the following traceback (Python 3.10/Windows server 2016):
```  File "C:\dev\python_env\prod\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "C:\dev\python_env\prod\lib\site-packages\urllib3\connectionpool …
```

fix: construct InfluxDBError without http response

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
tests/test_WriteApiDataFrame.py

Closes #377
1. Rollback regression caused by https://github.com/influxdata/influxdb-client-python/commit/500835f3b1d3b2b87214ede830b750a6018c0ca9#diff-02179d31a524332a9b64b57d464f6a56c0725daf636a4a410a20ed2aa71a43e0
2. Improve regex to match start field with null value

fix: serialization to DataFrame with nan values

---

CHANGELOG.md
influxdb_client/rest.py
tests/test_InfluxDBClient.py

Closes #383
Timeout can be specified as a float.

fix: timeout can be specified as a float

---

influxdb_client/client/query_api.py

Related to https://community.influxdata.com/t/python-client-query-data-frame-does-not-return-multiple-dataframes/22955
The multiple DataFrames are return when there are tables with different schema.

fix: multiple dataframes for tables with different schema

---

CHANGELOG.md
influxdb_client/client/influxdb_client.py

Closes #382 
Replace log in ping function by debug instead of error.

fix: ping function uses debug for log

---

CHANGELOG.md
influxdb_client/client/exceptions.py
influxdb_client/client/util/helpers.py
tests/test_Helpers.py

Closes #403
Add better error message when the used `token` doesn't have permission to read organizations.

chore: improve error message when the client cannot find org by name

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py

Closes #406 
Use `pandas.concat()` instead of deprecated `DataFrame.append()`:
https://pandas.pydata.org/docs/dev/whatsnew/v1.4.0.html#deprecated-dataframe-append-and-series-append

fix: use pandas.concat() instead of deprecated DataFrame.append()

---

CHANGELOG.md
docs/conf.py
influxdb_client/client/bucket_api.py
influxdb_client/client/delete_api.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/query_api.py
influxdb_client/client/write_api.py
tests/test_DeleteApi.py
tests/test_WriteApiDataFrame.py

Related to https://influxcommunity.slack.com/archives/CHQ5VG6F8/p1645606126853649
`DeleteApi` uses default value from `InfluxDBClient.org` if org parameter is not specified.

feat: DeleteApi uses default value from `InfluxDBClient.org` if org parameter is not specified

---

CHANGELOG.md
examples/README.md
examples/logging_handler.py
influxdb_client/__init__.py
influxdb_client/client/loggingHandler.py
influxdb_client/client/write/point.py
tests/test_loggingHandler.py
tests/test_point.py

Closes #364 
```python
import logging
from influxdb_client import InfluxLoggingHandler
handler = InfluxLoggingHandler(url="…", token="…", org="…", bucket="…")
handler.setLevel(logging.DEBUG)
influx_logger = logging.getLogger('…')
influx_logger.setLevel(logging.DEBUG)
influx_logger.addHandler(handler)
influx_logger.debug("mem,host=host1 used_percent=23.43234543")
```
- should the connection be checked on init?
- should the logger behave on errors (e.g. buffer till a connection can be reestablished)?

feat: Add InfluxLoggingHandler to use the InfluxClient in python native logging

---

CHANGELOG.md
docs/api.rst
examples/invocable_scripts.py
examples/query.py
influxdb_client/__init__.py
influxdb_client/client/flux_csv_parser.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/invocable_scripts_api.py
influxdb_client/client/query_api.py
influxdb_client/client/queryable_api.py
influxdb_client/domain/authorization.py
influxdb_client/domain/authorization_update_request.py
influxdb_client/domain/axis.py
influxdb_client/domain/dbrp.py
influxdb_client/domain/dbrp_create.py
influxdb_client/domain/error.py
influxdb_client/domain/line_protocol_error.py
influxdb_client/domain/line_protocol_length_error.py
influxdb_client/domain/task.py
influxdb_client/service/buckets_service.py
influxdb_client/service/users_service.py
tests/test_FluxCSVParser.py

1. Updated API to latest version.
2. Added InvocableScripts API to create, list, delete and invoke scripts by seamless way.3. 
3. `FluxCSVParser` is able to parse data without datatype annotations.

feat: add InvocableScripts API

---

CHANGELOG.md
influxdb_client/client/write_api.py
setup.py
tests/test_WriteOptions.py
tests/test_WritesRetry.py

Was getting this warning using the client with Python 3.9:
```
/lib/python3.9/site-packages/influxdb_client/client/write/retry.py:47: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
super().__init__(**kw)
```
This commit should fix things by moving to the new parameter name for `urllib3`.

fix: fix DeprecationWarning in write API

---

CHANGELOG.md
influxdb_client/client/util/helpers.py
tests/test_Helpers.py

Closes #424
Improved error message for lookup to organization.

chore: Improve error message if there is no organization with required name

---

tests/test_WriteApi.py

Fix tests to be compatible with InfluxDB 2.2.

fix(test): reflect changes in InfluxDB 2.2

---

CHANGELOG.md
README.rst
influxdb_client/client/influxdb_client_async.py
tests/test_InfluxDBClientAsync.py

Related to https://github.com/influxdata/influxdb-client-python/issues/205#issuecomment-1077819296
Checking if the `async` client is used in async context.

chore: check present for async context

---

CHANGELOG.md
influxdb_client/client/_base.py
setup.py
tests/test_InfluxDBClient.py
tests/test_InfluxDBClientAsync.py

Closes #442
Fixed initialisation of the client without auth credentials:
```python
from influxdb_client import InfluxDBClient
client = InfluxDBClient("localhost:8086")
```

fix: initialization of the client without auth credentials

---

CHANGELOG.md
README.rst
examples/import_data_set.py
examples/query_from_file.py
influxdb_client/client/util/date_utils.py
influxdb_client/client/write/point.py
notebooks/stock_predictions_import_data.py
setup.py
tests/test_DateHelper.py
tests/test_DeleteApi.py
tests/test_PandasDateTimeHelper.py
tests/test_QueryApi.py
tests/test_point.py

Closes #447
1. Remove `pytz` library which is not necessary dependency.

chore: remove `pytz` library

---

influxdb_client/client/util/date_utils.py

Related to https://github.com/influxdata/influxdb-client-python/issues/454

docs: how to serialize the query results to custom timezone

---

CHANGELOG.md
influxdb_client/client/_base.py
tests/test_QueryApi.py

Closes #455 
Fixed formatting `datetime` with nanoseconds to Flux AST.

fix: formatting nanoseconds to Flux AST

---

.github/dependabot.yml
docs/conf.py
influxdb_client/__init__.py
influxdb_client/_async/api_client.py
influxdb_client/_sync/api_client.py
influxdb_client/configuration.py
influxdb_client/version.py
setup.py
tests/test_WriteApiBatching.py

Added configuration for Dependabot.

chore: add configuration for Dependabot

---

CHANGELOG.md
README.rst
influxdb_client/client/_base.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/influxdb_client_async.py
tests/config.json
tests/test_InfluxDBClient.py

Closes #444
Added possibility to initialize client by json file.
The format of the `json` file is same as is produced by `influx config`: 
```console
influx config --json
```
```json
{
"url": "http://localhost:8086",
"token": "my-token",
"org": "my-org",
"active": true
}
```

feat: add possibility to initialize client by json file

---

CHANGELOG.md
README.rst
docs/api.rst
docs/conf.py
examples/query_response_to_json.py
influxdb_client/client/_base.py
influxdb_client/client/flux_csv_parser.py
influxdb_client/client/flux_table.py
influxdb_client/client/invokable_scripts_api.py
influxdb_client/client/query_api.py
influxdb_client/client/query_api_async.py
influxdb_client/client/warnings.py
tests/test_FluxCSVParser.py
tests/test_InfluxDBClientAsync.py
tests/test_QueryApiDataFrame.py

Closes #445 
Closes #446
1. `query()` function returns `TableList` instead of `List['FluxTable']`, `query_csv()` function returns `CSVIterator` instead of `csv.reader` => we are able to add additional functions for better procession of the query results 
1. Query results can be easily serialised into `list` of values and JSON:
1. CSV query results can be easily serialised into `list` of values and optionally spit out the headers: 
1. `query_data_frame()` function contains warning and updated doc about using `pivot() function` to optimal shaping of query results
```python
from influxdb_client import InfluxDBClient
with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
data_frame = client.query_api().query_data_frame('''from(bucket:"my-bucket …
```

feat(query): improve Query UX

---

.flake8
Makefile
setup.py
tox.ini

This adds a simple makefile to be able to install dependencies quickly,
install the library locally as editable for quick development,
lint the necessary files, and run tests with coverage.
It also removes the tox file in favor of a dedicated flake8 file to not
give the impression we are using tox in any way.
My hope is for this to be used during development, but want to
look at replacing some other commands during CI/test with this
as well to keep things in sync better. For now, this is primarily
to act as a helper to developers.

chore: add makefile to repo

---

docs/development.rst
docs/index.rst

Basic document on how to do development of the library itself.

docs: add doc on development the library

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py
tests/test_InfluxDBClient.py
tests/test_InfluxDBClientAsync.py

Closes #480
The HTTP response can be exhausted by logger, so we have to use data that has already been read.

fix: querying data if the `debug` is enabled

---

CHANGELOG.md
influxdb_client/client/util/date_utils.py

Closes #471 
Two python threads can call get_date_helper() simultaneously, causing a
partially-contstructed DateHelper object to be returned to the caller.

fix: parsing date fails due to thread race

---

CHANGELOG.md
examples/README.md
examples/write_batching_by_bytes_count.py

Closes #392
Added an example: `How to use RxPY to prepare batches by maximum bytes count.`

docs: add an example: How to use RxPY to prepare batches by maximum bytes count.

---

CHANGELOG.md
influxdb_client/client/tasks_api.py
tests/test_TasksApi.py

Closes #490 
Fixed creating `Task` with import statement:
```python
task_flux = 'import "http"\n\n' \
'from(bucket: "iot_center")\n' \
'    |> range(start: -30d)\n' \
'    |> filter(fn: (r) => r._measurement == "environment")\n' \
'    |> aggregateWindow(every: 1h, fn: mean)'
task = self.tasks_api.create_task_cron("my-name", task_flux, "10 0 * * * *", self.organization.id)
```

fix: creating `Tasks` with `import` statements

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Closes #473
Added warning for measurement name starts with `#`:
> The measurement name '#my_measurement' start with '#'.
>
> The output Line protocol will be interpret as a comment by InfluxDB. For more info see:
>    - https://docs.influxdata.com/influxdb/latest/reference/syntax/line-protocol/#comments

chore: add warning for measurement name starts with hash

---

CHANGELOG.md
README.rst
influxdb_client/client/flux_csv_parser.py
setup.py
tests/test_InfluxDBClientAsync.py

Closes #496
Use [aiocsv](https://pypi.org/project/aiocsv/) for parsing CSV response from InfluxDB.

fix: parsing response with new line in column [async/await]

---

influxdb_client/client/write_api.py

The `WriteType.asynchronous` should be deprecated because we already have correctly implement async/await version of the client - https://influxdb-client.readthedocs.io/en/stable/usage.html#how-to-use-asyncio.

docs: add deprecation warning for `WriteType.asynchronous`

---

CHANGELOG.md
influxdb_client/client/users_api.py
influxdb_client/service/users_service.py
tests/test_UsersApi.py

Related to https://influxcommunity.slack.com/archives/CHQ5VG6F8/p1662739448171649
1. Updated InfluxDB UsersAPI to latest version
1. Added possibility to update user's password by wrapped API:
```python
from datetime import datetime
from influxdb_client import InfluxDBClient, OrganizationsService, AddResourceMemberRequestBody
with InfluxDBClient(url="http://localhost:8086", token="my-token", org="my-org", debug=False) as client:
user = client.users_api().create_user(f"New User_{datetime.now().timestamp()}")
print(f"Created user: {user}")
orgs_service = OrganizationsService(client.api_client)
organization = orgs_service.get_orgs(org="my-org").orgs[0]
member = orgs_service.post_orgs_id_members(org_id=organization.id,
add_resource_member_request_body=
AddResourceMemberRequestBody(id=user.id)) …
```

feat: update user's password by `users_api`

---

tests/test_WriteApiDataFrame.py

Related to https://app.circleci.com/pipelines/github/influxdata/influxdb-client-python/2046/workflows/8fdf747c-83b7-4fed-a1e7-647c216f211f
Use correct `start` bound for `PeriodIndex` to be compatible with Pandas 1.5.
- https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

fix(tests): compatibility with Pandas 1.5

---

.circleci/config.yml

Use Python 3.8 image instead of Docker:19 to clarify which version of the Docker is used to build image.

chore(ci): use Python 3.8 image instead of Docker:19 to build lambda layer

---

CHANGELOG.md
influxdb_client/client/_base.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/influxdb_client_async.py
tests/test_InfluxDBClient.py
tests/test_InfluxDBClientAsync.py

Closes #506
This PR makes it possible for users to configure the client in this way:
```python
InfluxDBClient.from_config_file(retries=WritesRetry(total=3, retry_interval=1, exponential_base=2))
```

feat: allow to use client's optional configs for initialization from file or environment properties

---

CHANGELOG.md
influxdb_client/client/query_api_async.py
tests/test_InfluxDBClientAsync.py

Closes #511
Fixed exception propagation for asynchronous `QueryApi`. Others async APIs works correctly.

fix: exception propagation for asynchronous `QueryApi`

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py
tests/test_InfluxDBClientAsync.py

Closes #517
This PR fixes parsing query response for the `async` client if the CSV looks like:
```csv
#group,false,false,false,false,true,true,true
#datatype,string,long,dateTime:RFC3339,string,string,string,string
#default,_result,,,,,,
,result,table,_time,_value,_field,_measurement,type
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
,,0,2022-10-13T12:28:31.181418542Z,ÂÂÂ,value,async,error
...
```

fix(async): parsing query response with two-bytes UTF-8 character

---

CHANGELOG.md
README.rst
influxdb_client/_async/rest.py
influxdb_client/_sync/rest.py
influxdb_client/client/_base.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/influxdb_client_async.py
influxdb_client/configuration.py
tests/config-ssl-mtls-certs.ini
tests/test_InfluxDBClient.py

Closes #508
Add MTLS support to the InfluxDB Python client as already discussed inside the following [issue](https://github.com/influxdata/influxdb-client-python/issues/508).

feat: MTLS support for the InfluxDB Python client

---

CHANGELOG.md
influxdb_client/configuration.py
tests/test_InfluxDBClient.py

Closes #519
The `logging.StreamHandler(sys.stdout)` should appended only once into `Logger`.

fix: duplicated debug output

---

.circleci/config.yml
CHANGELOG.md
setup.py
tests/test_InfluxDBClient.py

1. Add Python `3.11` to CI and `setup.py`.
2. Fixed build for Python 3.7.15 - the newest `cimg/python:3.7` uses `Ubuntu 20.04.1` as a base image. This Ubuntu contains new version of `OpenSSL` which doesn't works with our dummy HTTP server.
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-python/2146/workflows/9624a90e-6cab-4289-9698-da317fc00e09/jobs/11860

chore: add supports for Python 3.11, fix build for Python 3.7.15

---

CHANGELOG.md
influxdb_client/client/influxdb_client.py
influxdb_client/client/influxdb_client_async.py

Closes #520
Fixed creating client instance from static configuration for type checking.

fix: creating client instance from static configuration

---

CHANGELOG.md
examples/asynchronous_management.py
influxdb_client/_async/api_client.py
influxdb_client/client/delete_api_async.py
influxdb_client/client/write_api_async.py
tests/test_InfluxDBClientAsync.py

This PR fixes the return type for `*_async(...)` methods in management API. The async management API returns required object not `tuple` with HTTP status and headers.

fix: HTTP request return type for Management API [async/await]

---

CHANGELOG.md
influxdb_client/_sync/rest.py

Refactor code to not deprecated variant:
The deprecation warning also causes failure of CI build:
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-python/2199/workflows/e1db935d-5dfd-4944-9beb-d113c4108e8b/jobs/12253

refactor: use `HTTResponse.headers` instead deprecated `HTTPResponse.getheaders()`

---

CHANGELOG.md
examples/query.py
influxdb_client/client/flux_table.py
tests/test_QueryApi.py

Closes #533 
The querying into CSV skip empty lines from InfluxDB response.
```csv
#datatype,string,long,dateTime:RFC3339,double,string
#group,false,false,false,false,true
#default,_result,,,,
,result,table,_time,_value,_field
,,0,2022-11-24T10:00:10Z,0.1,_1_current_(mA)
,,1,2022-11-24T10:00:10Z,4,_1_current_limit_(mA)
,,2,2022-11-24T10:00:10Z,1,_1_voltage_(V)
,,3,2022-11-24T10:00:10Z,1,_1_voltage_limit_(V)
,,4,2022-11-24T10:00:10Z,0,_2_current_(mA)
,,5,2022-11-24T10:00:10Z,0,_2_current_limit_(mA)
,,6,2022-11-24T10:00:10Z,0,_2_voltage_(V)
,,7,2022-11-24T10:00:10Z,0,_2_voltage_limit_(V)
#datatype,string,long,dateTime:RFC3339,string,string
#group,false,false,false,false,true
#default,_result,,,,
,result,table,_time,_value,_field
,,8,2022-11-24T10:00:10Z,K,type …
```

feat(query): query to csv skip empty lines

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

Closes #516
The users can specify integer types by:
```python
dict_structure = {
"measurement": "h2o_feet",
"tags": {"location": "coyote_creek"},
"fields": {
"water_level": 1.0,
"some_counter": 108913123234
},
"time": 1
}
point = Point.from_dict(dict_structure, field_types={"some_counter": "uint"})
```
**Documentation:**

feat: configure types of integers fields when initializing Point from `dict` structure

---

tests/test_WriteApiDataFrame.py
tests/test_point.py

The `numpy` no longer supports `np.float` type:
For more info see - https://numpy.org/doc/stable/release/1.24.0-notes.html
This PR also fixes CI builds:
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-python?branch=clarify-config-measurements

fix: numpy no longer supports `np.float` type

---

README.rst
influxdb_client/client/write_api.py

Clarify units for `flush_interval `, `jitter_interval` and `retry_interval `.

docs: clarify the unit of a parameter

---

CHANGELOG.md
README.rst
influxdb_client/client/write_api.py
setup.py
tests/test_WriteApiBatching.py

Closes #558
Introduces two levels of deadlock protection
* Traps exceptions thrown by callbacks and logs a warning
* Implements a maximum wait time during `close()`
The second change involves the introduction of a new WriteOption: `max_close_wait`. The default is set to 5 minutes, but can be overriden in the same manner as other write options.
Note: in order to allow the failure to be tested safely, `pytest-timeout` has been added as a test dependency.
- [x ] CHANGELOG.md updated
- [x ] Rebased/mergeable
- [x ] A test has been added if appropriate
- [x ] `pytest tests` completes successfully
- [x ] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

fix: prevent exceptions in callbacks from causing deadlocks

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py
tests/test_FluxCSVParser.py

Closes #550
The empty values in query results from serialization into Pandas DataFrame are returned as `numpy.NaN` values instead of `''` - empty string.

fix(data_frame): parsing empty query result value as `numpy.NaN`

---

CHANGELOG.md
influxdb_client/client/_base.py
influxdb_client/client/influxdb_client.py
influxdb_client/client/influxdb_client_async.py
tests/config2.ini
tests/test_InfluxDBClient.py

Closes #585
Possibility to precise which config name we want when loading from_config_file

feat: possibility to precise which config name to load when loading config from file

---

CHANGELOG.md
influxdb_client/client/write_api.py
influxdb_client/client/write_api_async.py
tests/test_gzip.py

Closes https://github.com/open-telemetry/opentelemetry-collector/issues/8114
`Content-Encoding: identity` is incorrect and must not be set. As a result, the client is failing to write metrics to the OpenTelemetry Collector v0.81.0
RFC snippet: https://github.com/open-telemetry/opentelemetry-collector/issues/8114#issuecomment-1643494516
This change removes the hardcoded `Content-Encoding: identity` so that the remote servers don't reject the request. The go library of influx-client also does not add this header.

fix: Remove Content-Encoding=Identity as the header as it violates the RFC

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py

fix: DataFrame write shows Future Warning.

---

CHANGELOG.md
examples/task_example.py
influxdb_client/client/tasks_api.py
tests/test_TasksApi.py

Closes #614
added `tasks_api.find_tasks_iter`

feat: task pagination

---

CHANGELOG.md
influxdb_client/client/write_api.py

Closes https://github.com/influxdata/influxdb-client-python/issues/561

fix: prevent creating unnecessary threads repeatedly

---

CHANGELOG.md
influxdb_client/client/write/point.py
tests/test_point.py

feat: Add `__eq__` implementation to class Point

---

CHANGELOG.md
influxdb_client/_sync/rest.py
tests/test_InfluxDBClient.py

Closes #630
Fixed logging HTTP requests without query parameters.

fix: logging http requests without query parameters

---

CHANGELOG.md
README.rst

Related #634
Removed unsupported text role :class:. For more info see https://docutils.sourceforge.io/docs/ref/rst/roles.html

fix: render README.rst at GitHub

---

CHANGELOG.md
influxdb_client/client/_base.py
influxdb_client/client/flux_csv_parser.py
influxdb_client/client/query_api.py
influxdb_client/client/query_api_async.py
setup.py
tests/test_FluxCSVParser.py
tests/test_InfluxDBClientAsync.py
tests/test_QueryApiDataFrame.py

Closes #621
Handles data with missing values when querying to data frames. The query functions `query_data_frame...` have new optional parameter `use_extension_dtypes`.
```python
def query_data_frame(self, query: str, org=None, data_frame_index: List[str] = None, params: dict = None,
use_extension_dtypes: bool = False):
...
def query_data_frame_stream(self, query: str, org=None, data_frame_index: List[str] = None, params: dict = None,
use_extension_dtypes: bool = False):
...
```
* when set to `True`, missing values are represented as `pandas.NA` and dtype of columns containing `<NA>` is of corresponding [nullable extension dtypes](https://pandas.pydata.org/docs/reference/arrays.html#objects) from `pandas` package (ie. `Int64`, `Float64`,`Boolean` etc). Missing value can be checked using …

fix: handle null values in data

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py

Related #637
Currently, the following warning for inplace methods in the upcoming Pandas 3.0 is triggered.
```
~/.venv/lib/python3.11/site-packages/influxdb_client/client/write/dataframe_serializer.py:237: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.
For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
```
The pull request silences the warning.

fix: Pandas 3.0 warning for inplace method

---

CHANGELOG.md
influxdb_client/client/write_api.py

Related #640
Dispose scheduler when disposing `write_api`.

fix: dispose window scheduler

---

.circleci/config.yml
CHANGELOG.md
scripts/ci-test.sh
setup.py
tests/test_InfluxDBClient.py
tests/test_QueryApiDataFrame.py
tests/test_Warnings.py
tests/test_WriteApiDataFrame.py

Closes #632
Add support from Python 3.12.

chore: add support for Python 3.12

---

CHANGELOG.md
influxdb_client/client/write/dataframe_serializer.py
tests/test_WriteApiDataFrame.py

Closes #590
Fixed serialisation Pandas NaN values into LineProtocol.

fix: serialize Pandas NaN values into LineProtocol

---

setup.py

This PR update jinja2 test dependency to resolve security issue - https://github.com/influxdata/influxdb-client-python/security/dependabot/2

chore(deps): update jinja2

---

CHANGELOG.md
influxdb_client/client/exceptions.py
influxdb_client/rest.py

Closes #602 
Replaces deprecated `urllib` lib calls:
* `HTTPResponse.getheaders()` with HTTPResponse.headers`
* `HTTPResponse.getheader(name, default)` with `HTTPResponse.headers.get(name, default)`

fix: deprecated urllib calls

---

CHANGELOG.md

Closes #622
This adds PEP 561 distributing and packaging type information, which specifically resolves issue with MyPy
`error: Skipping analyzing "influxdb_client": module is installed, but missing library stubs or py.typed marker [import-untyped]`
The required marker really is just an empty file `py.typed`. The same fix has been applied in v3 client.

fix: packaging type info

---

CHANGELOG.md
influxdb_client/client/util/date_utils.py

This PR changes the behavior of `get_date_helper` to prefer `datetime.datetime.fromisoformat` over `dateutil.parser` in Python 3.11 or higher.
According to https://github.com/closeio/ciso8601/blob/b17984f5b4c6db0ef596b4d31456c8a39ae278ee/why_ciso8601.md, `Since Python 3.11+, the performance of cPython's datetime.fromisoformat is now very good`. I did some quick testing and it seems to be on a par with `ciso8601`:
On Python 3.10 I've got ~37,5s and ~3,5s without and with `ciso8601` installed, respectively. On Python 3.11 I've got ~2,5s and ~2,6s without and with `ciso8601` installed, respectively.
Because `ciso` is no dependency, but an extra, not all users (including me) installed it. With this PR these users will get a better out-of-the-box performance for Python 3.11+ users.

perf: Prefer datetime.fromisoformat over dateutil.parse in Python 3.11+ 

---

CHANGELOG.md
README.md
examples/asynchronous.py
examples/example.py
examples/influx_cloud.py
examples/logging_handler.py
examples/write_structured_data.py
influxdb_client/client/write/point.py
tests/test_InfluxDBClientAsync.py
tests/test_MultiprocessingWriter.py
tests/test_PandasDateTimeHelper.py

refactor: to timezone specific datetime helper to avoid use deprecated functions

---

CHANGELOG.md
influxdb_client/client/write_api_async.py

Helps internal issue https://github.com/influxdata/idpe/issues/18710
InfluxDB v3 Serverless will soon return 201 or 204, in cases where InfluxDB v1 and v2 only return 204. This change anticipates this API change. Public docs will also be updated.
InfluxDB v3 Dedicated and Clustered already have this behavior, and it is already documented.
- n/a A test has been added if appropriate
- n/a Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)
- I'm an employee.

fix(write-api): accept 201 response to write

---

CHANGELOG.md
examples/import_data_set_multiprocessing.py

Closes #578
1. Fixed rx chain
2. Add new source of data => using gzip compression in example

fix: multiprocessing example

---

CHANGELOG.md
setup.py

Closes #666
Fixed adding py.typed into package.
Tested via:
```
mkdir typed
cd typed
python -m venv venv
. venv/bin/activate
python -m pip install git+https://github.com/influxdata/influxdb-client-python.git@typed-definition-setup.py
ls -l venv/lib/python3.11/site-packages/influxdb_client
```

fix: add py.typed to the package definition

---

CHANGELOG.md
influxdb_client/client/_base.py
tests/test_InfluxDBClient.py

fix: added type validation to an attribute in client object
It is possible to pass "None" by mistake to the InfluxDBClient object.
I propose to do a quick sanity check on it.
Traceback example:
client_obj = InfluxDBClient(url=url, token=token, org=org)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "vitaly.chait/.local/lib/python3.12/site-packages/influxdb_client/client/influxdb_client.py", line 63, in init
super().init(url=url, token=token, debug=debug, timeout=timeout, enable_gzip=enable_gzip, org=org,
File "vitaly.chait/.local/lib/python3.12/site-packages/influxdb_client/client/_base.py", line 56, in init
if self.url.endswith("/"):
^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
Exception ignored in: <function InfluxDBClient.del at 0x7ff5627789a0> …

fix: url attribute type validation

---

CHANGELOG.md
influxdb_client/client/flux_table.py
setup.py

Closes #674
```python
class FluxTable(FluxStructure):
def __init__(self) -> None:
self.columns: List[FluxColumn] = [] #<<<<---- Added this typing
self.records: List[FluxRecord] = []    #<<<<---- Added this typing
```
Testing found the following warnings:
1. duplicated import
```python
#setup.py
from pathlib import Path
from pathlib import Path #<<<<-------------deleted duplicated
```
There's still unrelated tests that are not passing
```make lint```

fix: linting at flux_table.py

---

CHANGELOG.md
influxdb_client/client/write_api_async.py
tests/test_InfluxDBClientAsync.py

Closes #669
- set argument `precision_from_point` in internal `_serialize` method to `True`.
- detect `WritePrecision` key in resulting payload
- use the key to set `precision` argument in call to internal `_write_service.post_write_async`
- update `test_write_points_different_precision` to cover more current possible values

fix: async write prec where DEFAULT_PRECISION should not be used

---

CHANGELOG.md
README.md
influxdb_client/client/flux_csv_parser.py

Closes #671
in `flux_csv_parser` catch `CancelledError` and `TimeoutError` and add a note to check the client `timeout` setting.

fix: catch CancelledError and TimeoutError and add note about timeout

---

CHANGELOG.md
examples/README.md
examples/authorizations.py
influxdb_client/client/authorizations_api.py
influxdb_client/domain/authorization.py
tests/test_AuthorizationApi.py

Closes #680
* Add type checks in constructor of Authorization
* verify `org_id` is a string
* verify `permissions` is a list
* Add type check in `authorizations_api.create_authorization` that argument passed as `authorization` is of type `Authorization`.
* Add `examples/authorizations.py`

chore: add type checks for Authorization with new example.

---

influxdb_client/client/influxdb_client.py

Closes #
Minor docstring typo/grammar correction

Minor docstring typo/grammar correction

---

CHANGELOG.md
pyproject.toml
setup.py
tests/test_Helpers.py

Close [695](https://github.com/influxdata/influxdb-client-python/issues/695)
- Move the "setuptools" package to build dependency to accommodate new check from the homeassistant library
_ Before the fix
_ After the fix: I think the new error message means we have had solved the dependency issue, check out "home-assistant-core/script/hassfest/requirements.py" line 169. The new error message is for the homeassistant team
_ My steps to reproduce the issue:
- Checkout [Home assistant core repo](https://github.com/home-assistant/core)
- Run "source venv/bin/activate"
- Run "python3 -m script.gen_requirements_all && pip3.13 install -r requirements_all.txt --break-system-package"
- Run "python3 -m script.hassfest --integration-path "home-assistant-core/homeassistant/components/influxdb" …

feat: move-setuptools-build-dependency
