influxdata/influxdb-client-python

CHANGELOG.md
influxdb2/client/write/point.py
influxdb2_test/test_point.py
scripts/swagger.yml

Drop NaN and infinity values from fields when writing to InfluxDB

---

influxdb_client/api_client.py
influxdb_client/configuration.py
openapi-generator/src/main/resources/python/__init__package.mustache
scripts/pom.xml

Configure OpenAPI generator to allow easily regenerate sources

---

CHANGELOG.md
README.rst
examples/influx_cloud.py

Add documentation about how to connect to Influx Cloud

---

CHANGELOG.md
influxdb_client/client/delete_api.py
influxdb_client/client/influxdb_client.py
tests/test_DeleteApi.py
tests/test_LabelsApi.py

feat: Add delete metrics support #31

---

CHANGELOG.md
README.rst
examples/query.py
influxdb_client/client/flux_csv_parser.py
influxdb_client/client/query_api.py
tests/test_QueryApiStream.py

Added support for streaming a query response

---

CHANGELOG.md
README.rst
examples/import_data_from_url.py
examples/import_data_set.py
examples/import_data_set_multiprocessing.py
influxdb_client/client/write/point.py
influxdb_client/client/write_api.py
notebooks/stock_predictions_import_data.py
tests/test_point.py

1. Optimised client for large amount of data
1. Optimised parsing into LineProtocol
1. Added example how to stream data into InfluxDB

fix: Optimised writes

---

.circleci/config.yml
CHANGELOG.md
scripts/ci-test.sh
scripts/influxdb-onboarding.sh
tests/config.ini
tests/test_WriteApi.py

chore(ci): testing over Python 3.6, 3.7 and 3.8

---

CHANGELOG.md
setup.py

Closes #57
The source distribution also contains: `requirements.txt`, `extra-requirements.txt` and `test-requirements.txt`.

fix: requirements file should be in sources distribution

---

CHANGELOG.md
influxdb_client/client/flux_csv_parser.py
tests/test_FluxCSVParser.py

fix: Correctly parse CSV where multiple results include multiple tables

---

README.rst

docs: add note how to install on windows

---

CHANGELOG.md
README.rst
examples/example.py
examples/import_data_set.py
examples/import_data_set_multiprocessing.py
examples/iot_sensor.py
examples/query.py
notebooks/stock_predictions_import_data.py

docs: clarifying how to use an org parameter

---

CHANGELOG.md
README.rst
examples/influxdb_18_example.py

docs: Clarify how to use a client with InfluxDB 1.8

---

README.rst
influxdb_client/client/write_api.py

Closes #165 
Updated docs with clarification how to flush data at the end of script.

docs: clarify how to flush data at the end of script

---

README.rst

Closes https://github.com/influxdata/docs-v2/issues/2064

fix 2 broken links

---

README.rst

@bednar, need to fix an issue with the last link - thank you!

change 1.8 link to correct 2.0 link

---

README.rst

Closes #266
Use install pip command compatible with `zsh` shell.

docs: use install pip command compatible with `zsh` shell

---

README.rst

This PR is a small suggestion to add a salient link to the API docs for the package near the top of the readme. This may help with the discoverability of this important information.
Closes #

make a more salient link to API docs

---

README.rst

Add documentation section to README.md in following structure:
```
This section contains links to the client library documentation.
- Product documentation, Getting Started
- Examples
- API Reference
- Changelog
```

docs: update links to documentation

---

.circleci/config.yml
CHANGELOG.md
setup.py

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
Closes #

Add Python 3.10 to build

---

CHANGELOG.md
examples/README.md
examples/task_example.py

Added an example how to create a task by API.

docs: add an example how to create a task

---

examples/README.md
examples/import_parquet.py

The example shows how to load Apache Parquet datafile, convert into Pandas and write into InfluxDB.

docs: add example how to write Apache Parquet data file

---

README.rst

Add missing space, without which where was broken formatting.

docs: Add missing space

---

README.rst

Closes #
_Briefly describe your proposed changes:_ Just removed one word

docs: remove word repetition

---

README.rst

Updated the links in the README pointing to specific code line numbers.

Update code link line numbers in README.rst

---

CHANGELOG.md

Added latest changes to upcoming release.

docs: add latest changes to upcoming release
